version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.local
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./scripts/wait.sh:/wait.sh"
      - ./packages/backend:/svr/app
      - /svr/app/node_modules
    networks:
      - network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - pg-db
    links:
      - pg-db

  pg-db:
    image: postgres:12-alpine
    restart: always
    container_name: pg-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - pg-db
    networks:
      - network

volumes:
  pgdata:
  pgadmin:

networks:
  network:
    driver: bridge
